version: '3'
services:

  app:
    build: .
    command: tail -F anything
    depends_on:
      - db
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache:/home/nens/.cache  # shared cache
  db:
    image: mdillon/postgis:9.3-alpine
    environment:
      POSTGRES_USER: 'flooding'
      POSTGRES_PASSWORD: 'flooding'
      POSTGRES_DB: 'flooding_lib'
      # PGDATA: '/var/lib/postgresql/data/pgdata'
